server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS